# Generated by Django 3.0.4 on 2020-05-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpInsert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiffin_type', models.CharField(max_length=100)),
                ('subtiffin_type', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_amount', models.IntegerField(max_length=100)),
            ],
            options={
                'db_table': 'ordernow',
            },
        ),
        migrations.CreateModel(
            name='OrderNow',
            fields=[
                ('ordernow_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tiffin_type', models.CharField(max_length=100)),
                ('subtiffin_type', models.CharField(max_length=100)),
                ('from_date', models.DateField(max_length=100)),
                ('to_date', models.DateField(max_length=100)),
                ('total_amount', models.IntegerField()),
            ],
            options={
                'db_table': '',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=100)),
                ('orderdate', models.DateField(max_length=100)),
                ('custname', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='societyname',
            fields=[
                ('soc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('soc_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'society',
            },
        ),
        migrations.CreateModel(
            name='UpdateTiffin',
            fields=[
                ('sub_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tiff_id', models.IntegerField()),
                ('sname', models.CharField(max_length=100)),
                ('samount', models.IntegerField()),
            ],
            options={
                'db_table': 'updatetiffin',
            },
        ),
    ]
