# Generated by Django 3.0.4 on 2020-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empinsert2'),
    ]

    operations = [
        migrations.CreateModel(
            name='carta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmenu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'menualcarta',
            },
        ),
    ]
