# Generated by Django 3.0.4 on 2020-05-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderdisplay'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderdisplay',
            table='ordernow2',
        ),
    ]
