# Generated by Django 3.0.4 on 2020-05-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200510_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdisplay',
            name='oid',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
