# Generated by Django 3.0.4 on 2020-05-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200510_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empinsert',
            name='user_id',
        ),
    ]
