# Generated by Django 3.0.4 on 2020-05-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_empinsert_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empinsert',
            name='id',
        ),
        migrations.AddField(
            model_name='empinsert',
            name='ordernow_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
