# Generated by Django 3.0.4 on 2020-05-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200512_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernow',
            name='created_by',
        ),
        migrations.AlterModelTable(
            name='empinsert',
            table='',
        ),
        migrations.AlterModelTable(
            name='ordernow',
            table='ordernow',
        ),
    ]
