# Generated by Django 3.0.4 on 2020-05-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ordernow_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernow',
            name='ordernow_id',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
