# Generated by Django 3.0.4 on 2020-05-12 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200512_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernow',
            name='ordernow_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
