# Generated by Django 3.0.4 on 2020-05-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200512_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='camount',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='cid',
        ),
        migrations.AddField(
            model_name='carta',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
