# Generated by Django 3.0.4 on 2020-05-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200513_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='menudisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mainmenu',
            },
        ),
    ]
