# Generated by Django 3.0.4 on 2020-05-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_menudisplay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menudisplay',
            name='id',
        ),
        migrations.AddField(
            model_name='menudisplay',
            name='mid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
