# Generated by Django 3.0.4 on 2020-05-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200516_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menudisplay',
            old_name='mdate',
            new_name='odate',
        ),
        migrations.RenameField(
            model_name='menudisplay',
            old_name='mid',
            new_name='otid',
        ),
        migrations.AlterModelTable(
            name='menudisplay',
            table='officetiffinmenu',
        ),
    ]
