# Generated by Django 3.0.4 on 2020-05-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200516_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='otdisplay',
            fields=[
                ('otid', models.IntegerField(primary_key=True, serialize=False)),
                ('Vegetarian1', models.CharField(max_length=100)),
                ('Mixed1', models.CharField(max_length=100)),
                ('Premium_Veg1', models.CharField(max_length=100)),
                ('Premium_Mixed1', models.CharField(max_length=100)),
                ('odate1', models.DateField()),
            ],
            options={
                'db_table': 'officetiffinmenu',
            },
        ),
        migrations.RemoveField(
            model_name='menudisplay',
            name='odate',
        ),
        migrations.RemoveField(
            model_name='menudisplay',
            name='otid',
        ),
        migrations.AddField(
            model_name='menudisplay',
            name='mdate',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menudisplay',
            name='mid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='menudisplay',
            table='mainmenu',
        ),
    ]
