# Generated by Django 3.0.4 on 2020-05-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200516_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='dtdisplay',
            fields=[
                ('dtid', models.IntegerField(primary_key=True, serialize=False)),
                ('Vegetarian', models.CharField(max_length=100)),
                ('Mixed1', models.CharField(max_length=100)),
                ('Premium_Veg', models.CharField(max_length=100)),
                ('Premium_Mixed', models.CharField(max_length=100)),
                ('ddate', models.DateField()),
            ],
            options={
                'db_table': 'dinnertiffinmenu',
            },
        ),
        migrations.CreateModel(
            name='ltdisplay',
            fields=[
                ('ltid', models.IntegerField(primary_key=True, serialize=False)),
                ('Vegetarian', models.CharField(max_length=100)),
                ('Mixed', models.CharField(max_length=100)),
                ('Premium_Veg', models.CharField(max_length=100)),
                ('Premium_Mixed', models.CharField(max_length=100)),
                ('ldate', models.DateField()),
            ],
            options={
                'db_table': 'lunchtiffinmenu',
            },
        ),
    ]
