# Generated by Django 3.0.4 on 2020-05-18 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0032_auto_20200517_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='alacartaorder',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('amenu', models.CharField(max_length=100)),
                ('aamount', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alacarta',
            },
        ),
    ]
