# Generated by Django 3.0.4 on 2020-05-26 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0035_useraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='sabji',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='sweets',
        ),
    ]
