# Generated by Django 3.0.4 on 2020-05-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200526_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='sabji',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carta',
            name='sweets',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
