# Generated by Django 3.0.4 on 2020-05-27 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200527_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='sabji',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='sweets',
        ),
    ]
