# Generated by Django 3.0.4 on 2020-05-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20200527_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carta',
            old_name='camount',
            new_name='aamount',
        ),
        migrations.RenameField(
            model_name='carta',
            old_name='cid',
            new_name='aid',
        ),
        migrations.RenameField(
            model_name='carta',
            old_name='cmenu',
            new_name='amenu',
        ),
        migrations.RemoveField(
            model_name='dtdisplay',
            name='Mixed',
        ),
        migrations.AlterModelTable(
            name='alacartaorder',
            table='',
        ),
        migrations.AlterModelTable(
            name='carta',
            table='alacarta',
        ),
    ]
