# Generated by Django 3.0.4 on 2020-05-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20200529_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carta',
            name='author',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='ramt',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='samt',
        ),
        migrations.RemoveField(
            model_name='carta',
            name='swamt',
        ),
    ]
