# Generated by Django 3.0.4 on 2020-05-31 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0041_auto_20200529_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='carorder',
            fields=[
                ('carid', models.IntegerField(primary_key=True, serialize=False)),
                ('carmenu', models.CharField(max_length=100)),
                ('carqty', models.IntegerField()),
                ('caramt', models.IntegerField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cartaorder',
            },
        ),
        migrations.DeleteModel(
            name='alacartaorder',
        ),
    ]
